
-- Connect as sysdba --
CREATE USER S_OWNER BY 123;
CREATE USER S_USER IDENTIFIED BY 798A;
CREATE USER S_L_USER IDENTIFIED BY 456ASDF;
CREATE USER S_N IDENTIFIED BY QWER;

GRANT CONNECT TO S_OWNER;
GRANT RESOURCE TO S_OWNER;
GRANT CREATE ANY VIEW TO S_OWNER;
GRANT CREATE ANY SYNONYM TO S_OWNER;
GRANT CONNECT TO S_USER;
GRANT CONNECT TO S_L_USER;
GRANT RESOURCE TO S_L_USER;

GRANT CONNECT TO S_N;
GRANT RESOURCE TO S_N;