
-- Connect as sysdba --
CREATE USER 'S_OWNER' IDENTIFIED BY '123';
CREATE USER 'S_USER' IDENTIFIED BY '798A';
CREATE USER 'S_L_USER' IDENTIFIED BY '456ASDF';
CREATE USER 'S_N' IDENTIFIED BY 'QWER';

GRANT CREATE VIEW ON *.* TO S_OWNER;
